name: CI

on:
  push:
    branches:
      - main
      - featHorusec
  pull_request:
    branches:
      - main

jobs:
  horusec-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Install Horusec
      run: |
        curl -fsSL https://horusec.io/bin/install.sh | bash

    - name: Run Horusec analysis
      run: horusec start -p . -e true