name: Horusec Analysis

on:
  push:
    branches:
      - main
      - featHorusec
  pull_request:
    branches:
      - main

jobs:
  horusec-analysis:
    name: Run Horusec Analysis
    runs-on: ubuntu-latest

    steps:
      # 1. Configurar el repositorio
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Instalar Horusec
      - name: Install Horusec
        run: |
          curl -fsSL https://horusec.io/bin/install.sh | bash
          echo "Horusec CLI installed successfully"
          export PATH=$PATH:/usr/local/bin

      # 3. Ejecutar análisis con Horusec
      - name: Run Horusec
        run: |
          /usr/local/bin/horusec start -p . --log-level=info --enable-owasp-dependency-check